---
title: "HomeWork"
format: 
  html: 
    toc: true
    toc-location: right
    toc-title: "Contents"
    toc-depth: 3
    number-sections: true
    smooth-scroll: true
editor: visual
---

# 관련 기술 정리

## 1. 회귀분석

### 🟥 릿지 회귀(Ridge Regression)

핵심 목적: 모든 변수를 조금씩 쓰되, 과도한 영향은 줄이자

#### 1) 사용 이유

변수들끼리 강하게 상관되어 있을 때

일반 선형회귀가 계수를 불안정하게 추정할 때

예측 성능을 안정화하고 싶을 때

#### 2) 사용 조건

변수 수가 많고 다중공선성이 심할때

모든 변수가 어느정도 의미가 있다고 믿을 때

해석보다 예측 성능이 중요한 경우

#### 3) 장단점

장점

계수 추정이 안정적

예측 성능이 좋음

상관된 변수들을 같이 살려둠

계산이 비교적 빠르고 안정적

단점

변수를 제거하지 못함

해석이 어려움

모델이 복잡해질 수 있음

#### 4) 사용된 연구

## 🟥 라쏘 회귀

#### 1) 사용이유

변수선택을 자동으로 하고싶을 때

중요하지 않은 변수를 아예 제거하고 싶을 때

모델을 단순하고 해석 가능하게 만들고 싶을 때

#### 2) 사용 조건

변수 수가 매우 많을 때

실제로 소수의 변수만 의미 있다고 생각할 때

논문에서 어떤 변수가 중요한가를 보여줘야할 때

해석 중심 분석(biomarker 탐색 등)

#### 3) 장단점

장점

변수 선택 가능

모델이 단순해짐

해석이 매우 쉬움

노이즈 변수 제거에 효과적

단점

상관된 변수들 중 하나만 랜덤하게 선택

선택이 데이터에 따라 불안정

예측 성능은 릿지보다 떨어질 수 있음

#### 4) 사용된 연구

### 🟥 엘라스틱 넷

핵심목적: 중요한 변수는 남기되, 상관된 변수들은 팀으로 데려가자

#### 1) 사용이유

릿지와 라쏘의 단점을 동시에 보완하고 싶을 때

변수 선택 + 안정성을 동시에 원할 때

상관된 변수 그룹을 같이 선택하고 싶을 때

#### 2) 사용 조건

변수 수가 많고

변수 간 상관도 크고

일부 변수만 중요할 가능성이 있을 때

#### 3) 장단점 

장점

변수 선택 가능

상관된 변수 그룹 유지

예측 성능과 해석의 균형

고차원 데이터에 매우 강함

단점

하이퍼파라미터가 2개 -\> 튜닝 필요

해석이 라쏘보다 약간 복잡

#### 4) 사용된 연구

doi:10.1001/jamapsychiatry.2024.4702
