---
title: "day1"
format:
  html: 
    toc: true
    toc-location: right
    toc-title: "Contents"
    toc-depth: 3
    number-sections: true
    smooth-scroll: true
  pdf: 
    toc: true
    toc-depth: 3
    number-sections: true
editor: visual
---

# Intro

## 변수 할당

```{r}
a = 10
a <- 10
print(a)
```

## 변수 연산

```{r}
b = 3
print(a + b)
print(a - b)
print(a * b)
```

# Data Analysis

## Package Load

`readxl` 패키지 불러오기

```{r}
require(base)
```

## Data Load

```{r}
data = iris
```

## Check variables'name

변수이름 확인하기

```{r}
names(data)
```

## Data summary

데이터 종류에 따른 데이터 요약

### Numerical Data

수치형 데이터 요약

```{r}
summary(data$Sepal.Length)
min(data$Sepal.Length) # 최솟값
max(data$Sepal.Length) # 최댓값
mean(data$Sepal.Length) # 평균
median(data$Sepal.Length) # 중위수
```

수치형 데이터 요약2

```{r}
x = data$Sepal.Length
summary(x)
min(x)
max(x)
```

### Categorical Data

범주형 데이터 요약

```{r}
y = data$Species
count = table(y)
print(count)
```

## Visualization

### Numerical Data

수치형 데이터의 산점도(scatter plot)

```{r}
plot(x)
```

수치형 데이터의 상자그림

```{r}
boxplot(x)
```

### Categorical Data

```{r}
y = data$Species
count = table(y)
pie(count)
```

```{r}
barplot(count)
```

## Statistical Analysis

### 평균 차이 비교
